{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "typescript-docker-multi-stage-build.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  # {{- if .Values.ingress.tls }}
  # tls:
  #   {{- range .Values.ingress.tls }}
  #   - hosts:
  #       {{- range .hosts }}
  #       - {{ . | quote }}
  #       {{- end }}
  #     secretName: {{ .secretName }}
  #   {{- end }}
  # {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "typescript-docker-multi-stage-build.fullname" $ }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
